spring:
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: event
        period: 5000
        strategy: refresh

---
spring:
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 3213
        strategy: refresh
  microservice-name: metricservice

---
spring:
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: event
        period: 5000
        strategy: refresh
  microservice-name: confighottest

---
spring:
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 3123
        strategy: refresh
  microservice-name: configpretest
