spring:
  microservice-name: sample-application-property-for-base-msa-framework
  datasource:
    dbcp2:
      initial-size: 20  
    platform: mariadb
    url: jdbc:mariadb://169.56.162.104:3306/instructor
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: qoxSVIJA8q

  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql

---
spring:
  datasource:
    dbcp2:
      initial-size: 20
    driver-class-name: org.mariadb.jdbc.Driver
    password: test
    platform: mariadb
    url: jdbc:127.0.0.1:3306
    username: tlc
  h2:
    console:
      enabled: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  microservice-name: servicetypetest
