apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: ibmc-file-bronze
