apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: microservice
        image: cloudsvcdev/microservice
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: system-config
        volumeMounts:
          - mountPath: /config
            name: app-config-volume
            readOnly: true
          - mountPath: /pattern
            name: pattern-config-volume
            readOnly: true
      - name: logging
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: FLUENTBIT_CONFIG
          value: fluent-bit.conf
        image: ilkrpg/fluent-bit:0.13.4_a
        ports:
        - containerPort: 2020
          protocol: TCP
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/data
          name: vardata
          readOnly: true
        - mountPath: /fluent-bit/etc/
          name: fluent-bit-sidecar-config
      volumes:
        - name: app-config-volume
          configMap:
            name: app-config
        - name: pattern-config-volume
          configMap:
            name: pattern-config
        - name: varlog 
          hostPath:
            path: /var/log
            type: ""
        - name: vardata
          hostPath:
            path: /var/data
            type: ""
        - name: fluent-bit-sidecar-config
          configMap:
            name: fluent-bit-sidecar-config
        