resources:
- deployment.yaml
- service.yaml
configMapGenerator:
- name : fluent-bit-sidecar-config
  files: 
  - filter-kubernetes.conf
  - fluent-bit.conf
  - input-kubernetes.conf
  - output-fluentd.conf
# configMapGenerator:
#   - name: system-config
#     literals:
#       - SPRING_CONFIG_LOCATION=classpath:/,classpath:/config/,file:/,file:/pattern/dbaccess.yaml,file:/pattern/messagechannel.yaml,file:/pattern/session.yaml,file:/pattern/cache.yaml,file:/pattern/metric.yaml,file:/pattern/log.yaml,file:/config/,file:/config/application-overlay.yaml