apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  serviceName: "headless"
  replicas: 3
  template:
    spec:
      containers:
      - name: microservice
        image: cloudsvcdev/microservice
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: system-config
