apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
        prometheus.io/port: '8091'
