apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8091
        name: microservice
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8091
