apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ibmc-file-bronze
  volumeMode: Filesystem
